//! Static game data: scenario definitions, country/province data, and the
//! RON loaders for them. This crate knows nothing about ECS or rendering.
//!
//! All gameplay content lives in `assets/data/` as RON files and is validated
//! at load time. Ids are newtyped so a ProvinceId can never be confused with
//! a CountryId at compile time.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;

#[derive(Debug, thiserror::Error)]
pub enum DataError {
    #[error("io error reading {path}: {source}")]
    Io {
        path: String,
        source: std::io::Error,
    },
    #[error("parse error in {path}: {source}")]
    Parse {
        path: String,
        source: ron::error::SpannedError,
    },
    #[error("validation error: {0}")]
    Validation(String),
}

/// Three-letter tag, e.g. "USA", "SOV", "PRC". Ordered so that iteration over
/// keyed maps is deterministic.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct CountryTag(pub String);

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct ProvinceId(pub u32);

/// Economic region (grid zone / logistics cluster). Generated by mapgen;
/// never crosses a country border.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, Default,
)]
pub struct RegionId(pub u16);

/// Extractable resource kinds with map locality (diffuse goods like grain
/// and manufactured goods are computed, not deposited).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum DepositKind {
    Coal,
    Oil,
    Iron,
    Uranium,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RegionDef {
    pub id: RegionId,
    /// Named after its most populous province.
    pub name: String,
}

/// The two poles of the Cold War plus the space in between.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Alignment {
    WesternBloc,
    EasternBloc,
    NonAligned,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CountryDef {
    pub tag: CountryTag,
    pub name: String,
    pub alignment: Alignment,
    /// National map color, sRGB. Distinct per country (political map mode).
    pub color: (u8, u8, u8),
    pub capital: ProvinceId,
    /// 0-100. How firmly the government controls the country.
    pub stability: u8,
    /// Starting industrial capacity (abstract units).
    pub industry: u32,
    /// Whether this country has nuclear weapons at scenario start.
    pub nuclear_power: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvinceDef {
    pub id: ProvinceId,
    pub name: String,
    pub owner: CountryTag,
    pub terrain: Terrain,
    /// (longitude, latitude) of the province center in degrees. Placeholder
    /// geometry until real polygons arrive via the mapgen tool.
    pub center: (f32, f32),
    /// Population in thousands.
    pub population_k: u32,
    /// Urban population in thousands (subset of population_k).
    #[serde(default)]
    pub urban_k: u32,
    /// Economic region this province belongs to.
    #[serde(default)]
    pub region: RegionId,
    /// Resource deposits (kind, abstract size 1-10).
    #[serde(default)]
    pub deposits: Vec<(DepositKind, u32)>,
    pub adjacent: Vec<ProvinceId>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Terrain {
    Plains,
    Forest,
    Hills,
    Mountain,
    Desert,
    Jungle,
    Urban,
    Marsh,
    Tundra,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScenarioDef {
    pub name: String,
    /// Start date as (year, month, day).
    pub start_date: (i32, u8, u8),
    pub description: String,
}

/// Presentation metadata for the nation-select screen. Researched per
/// nation as of the scenario start date; flag/portrait images live at
/// `assets/flags/<TAG>.png` and `assets/leaders/<TAG>.png`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NationMeta {
    pub tag: CountryTag,
    /// Proper period name, e.g. "Kingdom of Egypt".
    pub display_name: String,
    /// De-facto ruler at scenario start (not ceremonial figurehead).
    pub leader_name: String,
    pub leader_title: String,
    pub government: String,
    /// Two paragraphs of historic-situation text, second person.
    pub situation: String,
    /// Featured in the "interesting picks" quick selector.
    pub interesting: bool,
    /// One-line pitch for playing this nation.
    pub hook: String,
}

/// A scripted historical event.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventDef {
    pub id: String,
    pub trigger: EventTrigger,
    /// Daily chance to fire once the trigger condition holds (permille);
    /// absent = fires immediately when the condition holds.
    #[serde(default)]
    pub chance_permille: Option<u32>,
    pub title: String,
    /// Teletype-voice body text shown to the player.
    pub body: String,
    /// The country whose decision this is. None = world event
    /// (effects/options[0] apply immediately on firing).
    #[serde(default)]
    pub country: Option<CountryTag>,
    /// Days the deciding country has before option 0 auto-applies.
    #[serde(default)]
    pub deadline_days: u8,
    /// Choice options; the first is the default/historical choice.
    /// Events without options use `effects` directly.
    #[serde(default)]
    pub options: Vec<EventOption>,
    #[serde(default)]
    pub effects: Vec<EventEffect>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventOption {
    pub label: String,
    pub effects: Vec<EventEffect>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum EventTrigger {
    /// Fires at (year, month, day, hour).
    Date((i32, u8, u8, u8)),
    /// Fires N days after a war begins between the two countries.
    WarDaysElapsed {
        a: CountryTag,
        b: CountryTag,
        days: u16,
    },
    /// Fires when at least `count` of `owner`'s 1950 provinces are held
    /// by countries at war with `owner`.
    ProvincesLost { owner: CountryTag, count: u16 },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum EventEffect {
    AdjustTension(i32),
    DeclareWar {
        a: CountryTag,
        b: CountryTag,
    },
    /// Set a country's posture toward an enemy: "Advance" or "Hold".
    SetPosture {
        country: CountryTag,
        enemy: CountryTag,
        posture: String,
    },
    /// Transfer named provinces between owners (e.g. Hainan falls).
    TransferProvinces {
        from: CountryTag,
        to: CountryTag,
        names: Vec<String>,
    },
    /// Spawn formations (intervention forces). Province resolved by
    /// (owner_1950, name).
    SpawnForces {
        owner: CountryTag,
        province_owner: CountryTag,
        province: String,
        archetype: String,
        divisions: u32,
        quality: u32,
    },
    /// Patron military aid: add points to a country's military stockpile
    /// (the upkeep/raising currency). How PRK survives its own economy.
    GrantStock {
        country: CountryTag,
        amount: u64,
    },
    /// Declare a war aim: "StatusQuoAnte" | "Punish" | "NewLine" | "Unify".
    SetWarAim {
        country: CountryTag,
        enemy: CountryTag,
        aim: String,
    },
    /// International standing (UN mandates, coalition breadth).
    GrantLegitimacy {
        country: CountryTag,
        amount: i32,
    },
    /// Authorize the thermonuclear ("Super") follow-on program.
    AuthorizeThermonuclear {
        country: CountryTag,
    },
    /// Persistent nuclear-program speed modifier (espionage boosts,
    /// political acceleration). Permille, multiplicative with others.
    AdjustProgramSpeed {
        country: CountryTag,
        permille: u32,
    },
    /// Found a nuclear program (AI decisions, scripted starts).
    FoundNuclearProgram {
        country: CountryTag,
        route: String,
    },
}

/// A nation's nuclear-program state at scenario start (nuclear.ron).
/// Facility levels are abstract: one level of enrichment or reactor is
/// one Oak-Ridge/Mayak-scale complex increment.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NuclearSeedDef {
    pub country: CountryTag,
    /// "Founded" | "Producing" | "Tested"
    pub stage: String,
    /// "Plutonium" | "Heu" | "Both"
    pub route: String,
    pub stockpile: u32,
    pub assembled: u32,
    pub enrichment_level: u32,
    pub reactor_level: u32,
    /// Aggregate scientist skill (0-30).
    pub scientists: u32,
    /// Months until a queued reactor build completes (0 = none).
    pub building_reactor_months: u32,
    /// Thermonuclear program already authorized (USSR 1950).
    pub thermonuclear_authorized: bool,
    /// Strategic delivery: nuclear-capable bomber force and combat
    /// radius. Zero bombers = no delivery arm yet.
    #[serde(default)]
    pub bombers: u32,
    #[serde(default)]
    pub bomber_range_km: u32,
    /// Extra reach flying one-way missions (Tu-4 against CONUS).
    #[serde(default)]
    pub one_way_extra_km: u32,
    /// Countries whose territory hosts this nation's bombers.
    #[serde(default)]
    pub basing_rights: Vec<CountryTag>,
    /// Bomber generation growth: km of combat radius gained per year
    /// (B-47 -> B-52; Tu-4 -> Tu-16 -> Tu-95).
    #[serde(default)]
    pub range_growth_km_per_year: u32,
}

/// A starting army formation, resolved by (province name, owner) at load.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OobEntry {
    pub owner: CountryTag,
    /// Province name as in world.ron; must be unique within the owner.
    pub province: String,
    /// "Infantry", "Motorized", or "Armor".
    pub archetype: String,
    pub divisions: u32,
    /// Equipment/training quality, permille (1000 = nominal).
    pub quality: u32,
}

/// Everything loaded from disk for one scenario, validated and cross-linked.
#[derive(Debug, Clone)]
pub struct ScenarioData {
    pub scenario: ScenarioDef,
    pub countries: BTreeMap<CountryTag, CountryDef>,
    pub provinces: BTreeMap<ProvinceId, ProvinceDef>,
    /// Economic regions; may be empty for hand-authored test scenarios.
    pub regions: BTreeMap<RegionId, RegionDef>,
    /// Nation-select metadata; may be absent for minor tags (screen shows
    /// a stats-only fallback).
    pub nations_meta: BTreeMap<CountryTag, NationMeta>,
    /// Scripted events, sorted by date.
    pub events: Vec<EventDef>,
    /// Starting order of battle.
    pub oob: Vec<OobEntry>,
    /// Nuclear-program seeds (nuclear.ron; optional).
    pub nuclear: Vec<NuclearSeedDef>,
}

impl ScenarioData {
    /// Load a scenario from `assets/data/scenario/<name>/`.
    pub fn load(scenario_dir: &Path) -> Result<Self, DataError> {
        let scenario: ScenarioDef = load_ron(&scenario_dir.join("scenario.ron"))?;

        let mut countries = BTreeMap::new();
        let countries_dir = scenario_dir.join("countries");
        for entry in read_dir_sorted(&countries_dir)? {
            let defs: Vec<CountryDef> = load_ron(&entry)?;
            for def in defs {
                if countries.insert(def.tag.clone(), def).is_some() {
                    return Err(DataError::Validation(format!(
                        "duplicate country tag in {}",
                        entry.display()
                    )));
                }
            }
        }

        let mut provinces = BTreeMap::new();
        let provinces_dir = scenario_dir.join("provinces");
        for entry in read_dir_sorted(&provinces_dir)? {
            let defs: Vec<ProvinceDef> = load_ron(&entry)?;
            for def in defs {
                if provinces.insert(def.id, def).is_some() {
                    return Err(DataError::Validation(format!(
                        "duplicate province id in {}",
                        entry.display()
                    )));
                }
            }
        }

        // Regions file is optional (generated scenarios have it).
        let mut regions = BTreeMap::new();
        let regions_path = scenario_dir.join("regions.ron");
        if regions_path.exists() {
            let defs: Vec<RegionDef> = load_ron(&regions_path)?;
            for def in defs {
                regions.insert(def.id, def);
            }
        }

        // Events and order of battle are optional files.
        let mut events: Vec<EventDef> = Vec::new();
        let events_path = scenario_dir.join("events.ron");
        if events_path.exists() {
            events = load_ron(&events_path)?;
        }
        let mut oob: Vec<OobEntry> = Vec::new();
        let oob_path = scenario_dir.join("oob.ron");
        if oob_path.exists() {
            oob = load_ron(&oob_path)?;
        }
        let mut nuclear: Vec<NuclearSeedDef> = Vec::new();
        let nuclear_path = scenario_dir.join("nuclear.ron");
        if nuclear_path.exists() {
            nuclear = load_ron(&nuclear_path)?;
        }

        // Nation-select metadata is optional: the directory may not exist
        // yet, and coverage of minor tags may be partial.
        let mut nations_meta = BTreeMap::new();
        let nations_dir = scenario_dir.join("nations");
        if nations_dir.is_dir() {
            for entry in read_dir_sorted(&nations_dir)? {
                let metas: Vec<NationMeta> = load_ron(&entry)?;
                for meta in metas {
                    nations_meta.insert(meta.tag.clone(), meta);
                }
            }
        }

        let data = Self {
            scenario,
            countries,
            provinces,
            regions,
            nations_meta,
            events,
            oob,
            nuclear,
        };
        data.validate()?;
        Ok(data)
    }

    /// Resolve a province by (name, 1950 owner). Errors if missing or
    /// ambiguous — OOB and event references must be unambiguous.
    pub fn province_by_name(
        &self,
        owner: &CountryTag,
        name: &str,
    ) -> Result<ProvinceId, DataError> {
        let matches: Vec<ProvinceId> = self
            .provinces
            .values()
            .filter(|p| &p.owner == owner && p.name == name)
            .map(|p| p.id)
            .collect();
        match matches.as_slice() {
            [id] => Ok(*id),
            [] => Err(DataError::Validation(format!(
                "no province named {name:?} owned by {owner:?}"
            ))),
            _ => Err(DataError::Validation(format!(
                "ambiguous province {name:?} for {owner:?}"
            ))),
        }
    }

    fn validate(&self) -> Result<(), DataError> {
        for entry in &self.oob {
            self.province_by_name(&entry.owner, &entry.province)?;
            if !["Infantry", "Motorized", "Armor"].contains(&entry.archetype.as_str()) {
                return Err(DataError::Validation(format!(
                    "unknown archetype {:?}",
                    entry.archetype
                )));
            }
        }
        for event in &self.events {
            let all_effects = event
                .effects
                .iter()
                .chain(event.options.iter().flat_map(|o| o.effects.iter()));
            for effect in all_effects {
                match effect {
                    EventEffect::TransferProvinces { from, names, .. } => {
                        for name in names {
                            self.province_by_name(from, name)?;
                        }
                    }
                    EventEffect::SpawnForces {
                        province_owner,
                        province,
                        ..
                    } => {
                        self.province_by_name(province_owner, province)?;
                    }
                    _ => {}
                }
            }
        }
        for tag in self.nations_meta.keys() {
            if !self.countries.contains_key(tag) {
                return Err(DataError::Validation(format!(
                    "nation meta references undefined country {:?}",
                    tag
                )));
            }
        }
        for (tag, c) in &self.countries {
            if !self.provinces.contains_key(&c.capital) {
                return Err(DataError::Validation(format!(
                    "{:?}: capital {:?} is not a defined province",
                    tag, c.capital
                )));
            }
        }
        for (id, p) in &self.provinces {
            if !self.regions.is_empty() && !self.regions.contains_key(&p.region) {
                return Err(DataError::Validation(format!(
                    "province {:?}: region {:?} not defined",
                    id, p.region
                )));
            }
            if !self.countries.contains_key(&p.owner) {
                return Err(DataError::Validation(format!(
                    "province {:?}: owner {:?} is not a defined country",
                    id, p.owner
                )));
            }
            for adj in &p.adjacent {
                let neighbor = self.provinces.get(adj).ok_or_else(|| {
                    DataError::Validation(format!(
                        "province {:?}: adjacent {:?} does not exist",
                        id, adj
                    ))
                })?;
                if !neighbor.adjacent.contains(id) {
                    return Err(DataError::Validation(format!(
                        "adjacency not symmetric: {:?} -> {:?}",
                        id, adj
                    )));
                }
            }
        }
        Ok(())
    }
}

fn load_ron<T: serde::de::DeserializeOwned>(path: &Path) -> Result<T, DataError> {
    let text = std::fs::read_to_string(path).map_err(|source| DataError::Io {
        path: path.display().to_string(),
        source,
    })?;
    ron::from_str(&text).map_err(|source| DataError::Parse {
        path: path.display().to_string(),
        source,
    })
}

/// Directory listing with a stable order, so load results never depend on
/// filesystem enumeration order.
fn read_dir_sorted(dir: &Path) -> Result<Vec<std::path::PathBuf>, DataError> {
    let mut entries: Vec<_> = std::fs::read_dir(dir)
        .map_err(|source| DataError::Io {
            path: dir.display().to_string(),
            source,
        })?
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "ron"))
        .collect();
    entries.sort();
    Ok(entries)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_root() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
    }

    #[test]
    fn scenario_1950_loads_and_validates() {
        let dir = repo_root().join("assets/data/scenario/1950");
        let data = ScenarioData::load(&dir).expect("1950 scenario should load");
        assert_eq!(data.scenario.start_date, (1950, 1, 1));
        assert!(data.countries.contains_key(&CountryTag("USA".into())));
        assert!(data.countries.contains_key(&CountryTag("SOV".into())));
    }
}
